- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
- name: Generate password root for MySQL
  command: openssl rand -hex 7 creates=/root/.my.cnf
  register: mysql_new_root_password
- name: Show password MySQL
  debug:
    msg: password root MySQL adalah "{{ mysql_new_root_password.stdout }}"
  when: mysql_new_root_password.changed
- name: Install MySQL-Python
  apt:
    name: python-mysqldb
    state: present
- name: Remove test database
  mysql_db:
    name: test
    state: absent
- name: Remove user anonymous user mysql
  mysql_user:
    name: ''
    host_all: yes
    state: absent
- name: Rubah root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ root_db_password }}"
  loop:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
